version: "3.9"

services:
    web:
        image: reg.tribufu.com/img2txt-web
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3333:3333
        environment:
            PORT: 3333
